### PR TITLE
fix(): indent code and fix missing semicolon

### PR DESCRIPTION
**Pull request by Magicalex**
- fix "val already defined"
 - indent code (I followed the rules of editorconfig)
 - fix missing semicolon

### CODE REVIEW

**Comment by Magicalex** [comment]
@toopay any news?

**Comment by toopay** [comment]
@Magicalex I saw a bunch of spacing/indentations diff in the PR, make it harder to review the actual changes. Can you leave them as they were?

**Comment by Magicalex** [comment]
Yes I can leave them but I just follow rules in your .editorconfig

**Comment by acrobat** [comment]
You can check the diff with [`?w=0`](https://github.com/toopay/bootstrap-markdown/pull/243/files?w=0) at the end of the url to remove those space changes from the diff.

**Comment by toopay** [comment]
Thanks for the tip @acrobat, didn't know that query string option exists.

@Magicalex Can you please check all translations files as well? I see that you're only change some of them.

**Comment by Magicalex** [comment]
I check all translation files asap

**Comment by Magicalex** [comment]
Done!
I make a new PR because I changed of branch
new PR here : https://github.com/toopay/bootstrap-markdown/pull/249

**Pull request closed without merging**
