### PR TITLE
added scss

### PR DESCRIPTION
**Pull request by abixalmon**

### CODE REVIEW

**Comment by abixalmon** [comment]
Fixed all errors!

**Comment by toopay** [comment]
@acrobat Do you think `scss` will adds value? I personally do not think it is (i actually remove them in v1.x.x iirc). Thought?

**Comment by acrobat** [comment]
I think scss will add value becaus scss and less are overall the most used preprocessors. Another thing that puts me in favor of adding scss is that bootstrap is moving from less to sass/scss in bootstrap v4

> Moved from Less to Sass. Bootstrap now compiles faster than ever thanks to Libsass, and we join an increasingly large community of Sass developers.

It's your final call but I don't think it would harm to add `scss` support as we can reach more users with it!

**Comment by abixalmon** [comment]
I prefer using scss, it will be easier for developers who already use scss to compile this library together with their projects.

**Comment by MistaTwista** [comment]
I think there must be less and scss files, because i converted it right now for my project :) also bootstrap 4 as @acrobat said uses sass, and the project named bootstrap-markdown ;)

**Comment by toopay** [comment]
Thanks all.

**Pull request merged**
