### PR TITLE
Add onEndPreview callback (Issue #132)

### PR DESCRIPTION
**Pull request by tingley**
Add a callback that fires when the user exists Preview mode.

### CODE REVIEW

**Comment by lodev09** [comment]
I think it's better if you name the callback as `onPreviewEnd` for consistency purposes :)
@toopay

**Comment by toopay** [comment]
@tingley Can you please tweak the method name, as suggested?

**Comment by tingley** [comment]
Done, sorry for not noticing this earlier!

**Comment by toopay** [comment]
Thanks guys!

**Pull request merged**
